### ISSUE TITLE
chromium as editor does something weird with part activation or focus

### ISSUE THREAD

**Issue by jcompagner** [equoplatform/chromium-swt#86]
I will investigate this a bit further but our product uses a lot of selection events from 1 view to another
Like we populate the outline view or properties view based on selection change events that we fire from our own views (or the editor based on chromium)

problem is if i set the focus to the chromium editor (so i really click in side it). Then go back to a eclipse native view (ours or even standard eclipses once) that view/part doesnt seem to be really activated,, it is somewhere in the middle it seems to get the focus you can click around in it (for example our tree thing) but the selection events that it needs to fire where the properties or outline view is listenening to is not done. So that doesn't work,
I first need to click for example on the tab of that same view or in another view to get it working again..

as an example this commit is already a hack around that to get it correctly in our outline view implementation:

https://github.com/Servoy/servoy-eclipse/commit/e345338fbfa82a024ea63e63f54901dd5a1d4378

**Comment by Baytars** [comment]
Came across with the same issue. It cost a great deal of time for me to figure out what was happening. Is it an OS issue? Is it resulted from interruption of other plugins? Is it a drawback of IPartListener? Is it because I've wrappered the built-in browser and CEF browser for convenience of switching between them? Not at all! Finally I found out the truth after switching back to the built-in browser (org.eclipse.swt.browser.Browser).
It's Okay because the default engine the built-in browser Eclipse provides in Linux is Safari or Mozilla. I need a modern browser engine working fine with HTML5 and with less problem cooperating with Eclipse. At length I abandoned CEF.
As for solution, what about inheriting from the default browser class mentioned above to create the new child CEF Browser class? This should solve many issues which at present may not be attended to, and provide us with convenience of switching among different browser engines.
